void _puts_recursion(char *);
int _putchar(char c);
void _print_rev_recursion(char *);
int _strlen_recursion(char *);
int factorial(int n);
int _pow_recursion(int x, int y);
int sqrt_recursive(int, int, int);
int _sqrt_recursion(int);
int _prime_number(int, int);
int is_prime_number(int);
int is_palindrome_rec(char *, int, int);
int is_palindrome(char *);
